### ISSUE TITLE
Required options

### ISSUE THREAD

**Issue by ahume** [chrisnewtn/konfiga#3]
Did you consider allowing for required options, where this is no default? (throw if no value is retrieved from elsewhere). Thinking of a use-case where you have a secret that might be passed in via `env` or cmd line, but you wouldn't want to store in a configuration file.

**Comment by qubyte** [comment]
Right now we handle this by using a pair of fields. For example, for loggly we use a boolean `use-loggly` flag, and a `loggly-token` flag which defaults to an empty string (and a error is thrown by the application when the flag is `true` and the token is empty). This has served us well so far since it's been rare to use things which require a token in development, and features such as loggly are left turned off.

An example might be:

```javascript
const config = konfiga({
    useLoggly: {
        defaultValue: false,
        envVariableName: 'SOME_APP_USE_LOGGLY',
        cmdLineArgName: 'use-loggly',
        type: Boolean
    },
    logglyToken: {
        defaultValue: '',
        envVariableName: 'SOME_APP_LOGGLY_TOKEN',
        cmdLineArgName: 'loggly-token',
        type: String
    }
});

if (config.useLoggly && !config.logglyToken) {
    throw new Error('Missing loggly token.');
}

module.exports = config;
```

This is a little simplistic. We actually have a vizia logging module which takes configuration, and it works out if an error should be thrown in the specific case of loggly. The point more or less stands though.

That all said, it would be a nice feature to have! There may be cases when a sensible default can't be selected, no matter how careful we are.
